### PR TITLE
fixed MenuController: added variation for langId param

### PR DESCRIPTION
**Pull request by chemezov**
### What are you changing/introducing

fixed ResponseCache behavior variations: added variation for langId param.

### What is the reason for changing/introducing

The cache did not work correctly, did not depend on the langId parameter

### QA

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | no tests
| Fixed issues  | comma-separated list of tickets # fixed by the PR, if any

### CODE REVIEW

**Comment by nadar** [comment]
Thanks @chemezov 

We could also add all query params as cache viration, like 

```
`variations' => Yii::$app->request->get()
```

What do you think?

**Comment by chemezov** [comment]
@nadar , I agree, it would be appropriate. Also added line to CHANGELOG, maybe missed the version.

**Comment by nadar** [comment]
Thanks, actually its not yet released, so no changelog required. but i am going to release that package next week

**Comment by chemezov** [comment]
Thanks!

**Pull request merged**
